### PR TITLE
add support for adsense ads at the bottom of posts

### PR DESCRIPTION
**Pull request by acdoussan**
## Description

Implements https://github.com/cotes2020/jekyll-theme-chirpy/issues/669

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How has this been tested

- [x] I have run `bash ./tools/test` (at the root of the project) locally and passed
- [x] I have tested this feature in the browser
- [x] I have made these changes on my local blog, deployed it, and gotten my adsense account approved and ads are being served

### Test Configuration

- Browser type & version: Chrome
- Operating system: macOS
- Ruby version:  ruby 3.1.2p20
- Bundler version:  Bundler version 2.1.4b
- Jekyll version:  jekyll (4.3.2)

### CODE REVIEW

**Comment by acdoussan** [comment]
Commit signing looks annoying, don't really want to set that up, can that be ignored? Don't really understand the point, PR coming from my account, if I have access to my account, I have access to set up commit signing.

**Comment by cotes2020** [comment]
Not going to merge this feature, please leave it on your branch. Thanks!

**Comment by acdoussan** [comment]
Any specific reason? There wasn't any pushback on the feature req, was just auto-closed.

I've been holding out on creating a new blog so that I don't have to duplicate this in both places.

**Comment by qureshiaquib** [comment]
Is there any guidance to include advertisement and monitize my blog?
This feature is a must have feature.

**Comment by SoumyaK4** [comment]
> I'm not a dev. 

I don't know of any Jekyll theme that has an ad serving feature included, if you're not a dev, try something like wordpress instead, as you can use plugins to get any feature you want easily.

**Pull request closed without merging**
