### PR TITLE
feat: add post views counter for GoatCounter

### PR DESCRIPTION
**Pull request by kungfux**
## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Description
I've integrated and use GoatCounter for a while in my own codebase and since GoatCounter have been integrated into Chirpy, I'd like to incorporate changes for the post views counter. Other people also want this feature according to ref #1532.

## Implementation
First, we need to connect GoatCounter in the config, and then enable views counter by specifying the source provider for it like it is done for comments. This is how it looks like in the UI currently.

image

## Ideas
- Since it takes time to retrieve the data from counter provider, I'm not happy to show "0 views" initially and so I may suggest to hide views counter initially and then display it once actual views number is available by applying `visibility: hidden` and `visibility: visible` styles to a parent `span` element. Here is an [example](https://github.com/kungfux/kungfux.github.io/commit/ac2aee9603e32a671f8dd123e095381970eeba7a).

## Additional context
Since I was surprised to find localized string `pageview_measure`, I suspect you may have other plans for the same feature in mind, or have passed similar way in the past that you can share. Anyways, let me know what do you think once you have a time. Thanks.

### CODE REVIEW

**Review by cotes2020 — CHANGES_REQUESTED** [review]
Thank you so much! While I didn't actually use a GoatCounter ID to test the code, I'm sure it's available. Also, I have a couple ideas to share with you:

1. For the UI design, I think the location of the view count would be more appropriate to the right of the reading time.

    pv


2. The reference to the JS of GoatCounter pageviews should be placed in `_includes/js-selector.html`, which will bring better web page rendering performance.

3. The number to initialize the view count could be set to `1` instead of `0`.

4. i18n's `pageview_measure` was once used for Google Analaytics pageviews reporting, this feature was removed in #1071 as UA was deprecated. i18n keeps it for future pageviews services (like goatcounter now).

**Comment by cotes2020** [comment]
> 1. For the UI design, I think the location of the view count would be more appropriate to the right of the reading time.
> 
>    pv

I'd like to change the above comment: placing views to the left of the reading time is the way to go, otherwise it will cause jitters in the nearby text (reading time) due to JS modifying the number.

Updated:

pv-edited

**Comment by kungfux** [comment]
Thank you for taking the time to review the suggested changes and for sharing great ideas.

I've made suggested changes for UI and JS injection location. Please take a quick look. Thank you very much.

**Review by cotes2020 — COMMENTED** [review]
Since we now have multiple web analytics options, wouldn't it be a good idea to improve the configured options to make it more compact similar to the comment system.

`_config.yml`:

```yaml
# Web Analytics Settings
analytics:
  provider: # [google | goatcounter]
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
    pv:
      enabled: # boolean, the option for the post views counter, keep empty means disable
```

`_includes/` folder:

```
_includes/
└── analytics
    ├── goatcounter.html
    └── google.html
```

But doing so would require refactoring the existing google analytics code, what do you think?

**Comment by kungfux** [comment]
Sure, I like the idea of merging configuration settings to have everything in a single configuration section.

The only thing I would suggest changing is to allow using both analytics platforms at the same time.

However, I wonder how breaking configuration changes will be released? Will it be part of a major release or will changes need to be back-compatible? How do you usually do?

**Comment by cotes2020** [comment]
I favor the idea of using multiple analytics platforms at the same time, in which case the settings would have to be designed as:

```yaml
## _config.yml

# Web Analytics Settings
analytics:
  google:
    id: # fill in your Google Analytics ID
  goatcounter:
    id: # fill in your GoatCounter ID
```

Since pageviews can only display data from a single platform, the config options would be:

```yaml
## _config.yml

# Pageviews settings
pageviews:
  provider: # [google | goatcounter]
```

Generally speaking, breaking changes should be released in the MAJOR version, and strictly enforcing this guideline would result in too many major releases. So for this feature, I prefer to release it on the MINOR version, and remind users of the changes in the release note.

**Comment by kungfux** [comment]
Sounds good. Thanks.

Configuration changes have been implemented and seems to work as expected. Please have a look.

**Comment by cotes2020** [comment]
I've done a lot of refactoring, so if there are any thoughts on this, please let me know.

**Comment by kungfux** [comment]
The only thought is: It's nicely done 👍

I have enjoyed the solution with the spinner 🤩 and learnt something new. Thank you.

**Review by cotes2020 — APPROVED** [review]

**Pull request merged**
