### PR TITLE
Fix script location and URL encode share links

### PR DESCRIPTION
**Pull request by ZakKemble**
## Description

Theme toggle JS code was in between head and body tags (invalid placement), now moved to the head.

Share links now use `url_encode` instead of `escape` since the latter doesn't encode spaces and other special characters like '&' are encoded as HTML entities instead of % values (a post title containing an '&' will be cut short).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How has this been tested

- [ ] I have run `bash ./tools/deploy.sh --dry-run` (at the root of the project) locally and passed
- [x] I have tested this feature in the browser

### Test Configuration

- Browser type & version: Firefox 97.0.1
- Operating system: Windows 10
- Ruby version: 2.7.4p191
- Bundler version: 2.3.8
- Jekyll version: 4.2.1

### Checklist

- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by cotes2020 — CHANGES_REQUESTED** [review]
Nice patch! But there is a change request: is it possible to rewrite the commit message according to the [Conventional Commits Specification](https://conventionalcommits.org/)? since this project started using `standard-version` to generate the changelogs.

**Comment by ZakKemble** [comment]
Sure, updated commit messages.

**Review by cotes2020 — CHANGES_REQUESTED** [review]
CI failed, please lowercase the first letter of the `<description>`:

```
# Note: The structure of Conventional Commits 
<type>[optional scope]: <description>
```

**Comment by ZakKemble** [comment]
Done, but editing the commit message decided not to work the second time. Ended up having to revert and commit the changes again.

**Comment by ZakKemble** [comment]
I think I'll re-create the branch...

**Comment by cotes2020** [comment]
> Done, but editing the commit message decided not to work the second time. Ended up having to revert and commit the changes again.

There is no need to revert because GitHub allows multiple edits to commit message :)

**Comment by ZakKemble** [comment]
Yes, but it decided to stop working on my end :/

**Pull request closed without merging**
