### PR TITLE
Fix SW Error: Request method 'POST' is unsupported

### PR DESCRIPTION
**Pull request by xcaro**
## Description

Fix issue related to Service Worker

image

e.g. Fixes #(issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How has this been tested
- [x] N/A
## #Test Configuration
- [x] N/A
### Checklist
- [x] N/A

### CODE REVIEW

**Review by cotes2020 — COMMENTED** [review]
Thanks for the PR!

I think the reason for this error is that `sw.js` (service worker) stores the `Request` with the POST method as the key, which is not supported by the Web API.

Simply removing the POST request url (starting with the Google Analytics domain) did not completely solve this problem, so I think that improving the caching strategy of `sw.js` is a better way.

**Comment by xcaro** [comment]
Hi @cotes2020 ,

I'm not specialist on it. Can you suggest some idea to improve the caching?

Thanks,

**Comment by cotes2020** [comment]
My solution is 2f2832c

**Comment by xcaro** [comment]
This is looking really good solution.

Thanks you @cotes2020 ,

**Pull request closed without merging**
