### PR TITLE
Add maskable icons

### PR DESCRIPTION
**Pull request by Periecle**
## Description

Maskable icons is a new icon format that ensures that your PWA icon looks great on all Android devices. On newer Android devices, PWA icons that don't follow the maskable icon format are given a white background. When you use a maskable icon, it ensures that the icon takes up all of the space that Android provides for it.

Details on [web.dev](https://web.dev/maskable-icon-audit/?utm_source=lighthouse&utm_medium=devtools).

## Type of change

Added "purpose" property for icons with valid values

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How has this been tested

- [x] I have run `bash ./tools/deploy.sh --dry-run` (at the root of the project) locally and passed
- [x] I have tested this feature in the browser

### Test Configuration

- Browser type & version: Chrome Version 97.0.4692.71 (Official Build) (64-bit)
- Operating system: Windows 11
- Ruby version: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x64-mingw32]
- Bundler version: 2.3.4
- Jekyll version: 4.2.1

### Checklist

- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by cotes2020 — COMMENTED** [review]
Chrome (Version 97.0.4692.71) warns that `purpose: "any maskable" is discouraged`:
warning

**Comment by Periecle** [comment]
I have no warnings in the same version of chrome.  Could you please share details about this warning

**Comment by cotes2020** [comment]
It looks like you haven't tested the PWA locally, here are some details:

1.  Run the following command:
    ```
    $ JEKYLL_ENV=production bundle exec jekyll s
    ```
2. Navigate to <http://localhost:4000> with Chrome
3. Open Chrome DevTools > _Application_ > _Manifest_ > Boom, meet the warnings

**Comment by Periecle** [comment]
Indeed, we should generate two copies for each icon with "any" and "maskable" purposes, first without padding and second with padding. I think PR in its current state can be closed.

**Pull request closed without merging**
