### PR TITLE
style(scss): Fix various accessibility issues

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
## Description

This improves the contrast of certain text elements to make it easier to read.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactoring and improving code)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Additional context

Fixes https://github.com/cotes2020/jekyll-theme-chirpy/issues/1095

## How has this been tested

- [ ] I have run `bash ./tools/test` (at the root of the project) locally and passed
- [x] I have tested this feature in the browser

Do note that I haven't generated the website as it doesn't work for me on neither this branch and the `master` branch. I used Firefox DevTools. 

Using https://orowith2os.gitlab.io/posts/Flatpak-an-insecurity-nightmare as an example:

| Before | After |
|-----------|---------|
| image | image |
| image | image |

### CODE REVIEW

**Comment by TheEvilSkeleton** [comment]
To do:
- [ ] The other sidebar 
image
- [ ] Bottom section the article and footer 
image

**Comment by sublimeclemency** [comment]
@TheEvilSkeleton thanks for the effort. this helps me with my own blog css styles. please continue!

**Comment by TheEvilSkeleton** [comment]
> In the first commit of this draft, you changed `_sass/addon/module.scss` `%sidebar-links` to make the color `darkgray`. this only has a good effect in dark mode.

Good point, thanks!

**Comment by TheEvilSkeleton** [comment]
I bumped the contrast of `--text-color` so that `--text-muted-color` could be bumped as well. To be honest, I think it looks better that way.

**Comment by TheEvilSkeleton** [comment]
| Before | After |
|-----------|---------|
| image | image |
| image | image |

**Comment by TheEvilSkeleton** [comment]
@sublimeclemency it's ready for review

**Comment by Mohamed3nan** [comment]
can we make all edits to this file "\assets\css\style.scss" ? or it's for something else?

```scss
---
---

@import '{{ site.theme }}';

/* append your custom style below */
```

instead of editing the core theme!

**Comment by TheEvilSkeleton** [comment]
The goal is to fix various accessibility issues within the core theme.

**Pull request closed without merging**
