### PR TITLE
Added Burmese translation and locales

### PR DESCRIPTION
**Pull request by brootware**
## Description

Added a burmese language translation yml file.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How has this been tested

- [ ] I have run `bash ./tools/deploy.sh --dry-run` (at the root of the project) locally and passed
- [ ] I have tested this feature in the browser
- [x] Not applicable

### Test Configuration

- Browser type & version:
- Operating system:
- Ruby version: 
- Bundler version: 
- Jekyll version: 
- [x] Not applicable

### Checklist

- [x] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by cotes2020 — COMMENTED** [review]
Thanks for the translation! I'm not familiar with Burmese, I can find `my` in the IOS language table, but not `my-MY`. The closest I can find so far is `ms-MY`, but it's in Malay. So are you sure that `my-MY` is correct? If you are not sure, could you consider changing it from `my-MY` to `my`?

**Comment by digitigradeit** [comment]
> The closest I can find so far is `ms-MY`, but it's in Malay. So are you sure that `my-MY` is correct? If you are not sure, could you consider changing it from `my-MY` to `my`?

https://lh.2xlibre.net/locale/my_MM/
https://www.localeplanet.com/icu/iso639.html#my

The correct locale for Burmese Myanmar is my_MM: my - Burmese, MM - Burmese Myanmar

ms is Malaysaian

**Comment by brootware** [comment]
Thank you @digitigradeit and @cotes2020 , will push a new commit soon to rename the file.

**Review by brootware — COMMENTED** [review]
changed file name to my-MM

**Review by cotes2020 — APPROVED** [review]

**Pull request merged**
