### PR TITLE
Update sidebar, topbar, post to HTML5 elements

### PR DESCRIPTION
**Pull request by ottohellwig**
## Description

Updated div elements in _layouts/post.html, _includes/topbar.html, and sidebar.html to use HTML5 elements (article, nav, header). Motivation from Issue: Use HTML5 elements: header, nav, aside, main, article, section #1196.

## Type of change

- [x] Improvement (refactoring and improving code)

### CODE REVIEW

**Review by cotes2020 — CHANGES_REQUESTED** [review]
Thanks for your improvements!

But it seems that you broke the original code indentation, which makes it difficult to review the code. Please restore the original indentation.

**Comment by ottohellwig** [comment]
Sorry! I will make sure to turn Prettier off and use the original code indentation. Thanks.

**Review by cotes2020 — COMMENTED** [review]
Looks like there's still a lot of work to do. See also: <https://www.freecodecamp.org/news/semantic-html-alternatives-to-using-divs>

**Comment by cotes2020** [comment]
I apologize that this PR will not be merged. I took the time to implement semantic HTML more fully in PR #1207.

If you are interested, you can review #1207 before it is merged.

**Pull request closed without merging**
