### PR TITLE
chore: add npm commands to action

### PR DESCRIPTION
**Pull request by joshjohanning**
## Description

After updating to 5.6.0, my GitHub Actions build failed: https://github.com/joshjohanning/joshjohanning.github.io/actions/runs/4451432318/jobs/7818071037

It works when I add these commands: https://github.com/joshjohanning/joshjohanning.github.io/actions/runs/4451583589

These were the errors (not finding the `/assets/js/dist*`

```
- _site/404.html
  *  internal script /assets/js/dist/page.min.js does not exist (line 1)
- _site/about/index.html
  *  internal script /assets/js/dist/page.min.js does not exist (line 1)
- _site/archives/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/actions/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/advanced-security/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/azure-devops/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/azure/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/codespaces/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/dependabot/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/front-door/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/github/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/index.html
  *  internal script /assets/js/dist/categories.min.js does not exist (line 1)
- _site/categories/integrations/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/migrations/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/packages/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/pipelines/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/scripts/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/categories/work-items/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/page2/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/page3/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/page4/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/page5/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/posts/actions-runner-controller-without-cert-manager/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1[15](https://github.com/joshjohanning/joshjohanning.github.io/actions/runs/4451432318/jobs/7818071037#step:6:16))
- _site/posts/agent-pool-error/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/angular-tokenization/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 155)
- _site/posts/authorize-azure-artifacts-in-github-actions/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 155)
- _site/posts/azdo-angular-pipeline-caching/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 47)
- _site/posts/azdo-commit-message-validator-and-pr-linker-github-action/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 39)
- _site/posts/azdo-delete-custom-field/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 9)
- _site/posts/azure-devops-code-coverage/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 73)
- _site/posts/azure-devops-migrate-work-items/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 55)
- _site/posts/azure-frontdoor-preview-experience/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 237)
- _site/posts/dependabot-reusable-workflows/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 45)
- _site/posts/dependency-review-action/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 23)
- _site/posts/deprecated-github-actions-commands/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 27)
- _site/posts/extends-template/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 345)
- _site/posts/gh-auth-login-in-actions/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 81)
- _site/posts/github-advanced-security-feature-chart/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/github-advanced-security-permissions-chart/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/github-approveops/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 105)
- _site/posts/github-apps/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 107)
- _site/posts/github-code-coverage/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 91)
- _site/posts/github-codeql-ignore-files/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 121)
- _site/posts/github-codeql-pr/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 125)
- _site/posts/github-codespaces-powerlevel10k/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 103)
- _site/posts/github-connecting-to-azure-boards-multiple-orgs/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/github-container-jobs/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 95)
- _site/posts/github-delete-branch-protection-rules/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 155)
- _site/posts/github-dependabot-for-actions/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 55)
- _site/posts/github-dependabot-with-azure-artifacts/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 81)
- _site/posts/github-download-from-github-packages/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 363)
- _site/posts/github-download-latest-release/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 7)
- _site/posts/github-misc-scripts/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/github-packages-migrate-nuget-packages-to-github-packages/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 85)
- _site/posts/github-packages-migrate-nuget-packages/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 69)
- _site/posts/github-script-to-add-users-to-teams/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 9)
- _site/posts/github-script-to-delete-repos/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 11)
- _site/posts/lap-around-github-advanced-security/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/migrate-azure-devops-work-items-to-github-issues/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/migrate-svn-to-git/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 45)
- _site/posts/migrating-repos-to-github/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 49)
- _site/posts/my-macos-development-environment/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 43)
- _site/posts/nuget-pusher-script/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 93)
- _site/posts/pipeline-templates/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/reparent-work-items/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 79)
- _site/posts/security-alerts/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 1)
- _site/posts/trac-to-github/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 19)
- _site/posts/using-github-checks-api/index.html
  *  internal script /assets/js/dist/post.min.js does not exist (line 239)
- _site/speaking/index.html
  *  internal script /assets/js/dist/page.min.js does not exist (line 1)
- _site/tags/actions-runner-controller/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/angular/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/artifactory/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/azure-artifacts/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/azure-boards/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/azure-devops/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/azure-front-door/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/azure/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/branch-protection-rules/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/chatops/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/code-coverage/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/codeql/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/containers/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/dependabot/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/gh-cli/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/git/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/github-actions/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/github-advanced-security/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/github-apps/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/github-codespaces/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/github-issues/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/github-packages/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/github/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/index.html
  *  internal script /assets/js/dist/commons.min.js does not exist (line 1)
- _site/tags/issueops/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/maven/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/migrations/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/nuget/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/pipeline-templates/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/pipelines/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/policy-enforcement/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/pull-requests/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/releases/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/scripts/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/secret-scanning/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/svn/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/tfvc/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/vs-code/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)
- _site/tags/work-items/index.html
  *  internal script /assets/js/dist/misc.min.js does not exist (line 1)

HTML-Proofer found [109](https://github.com/joshjohanning/joshjohanning.github.io/actions/runs/4451432318/jobs/7818071037#step:6:110) failures!
Error: Process completed with exit code 1.
```

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How has this been tested

- [x] I have run `bash ./tools/test` (at the root of the project) locally and passed
- [x] I have tested this feature in the browser

### Test Configuration

n/a

### CODE REVIEW

**Review by cotes2020 — COMMENTED** [review]
No need to build JS on the user end. These JS files are already inside the gem.

See also: https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

**Comment by joshjohanning** [comment]
Hmm....

When I brought in the 5.6.0 changes, my website didn't work until I locally ran a `npm run build` command because in this commit b69d3d7eddc3720df012931214dca8611cee3da8, you delete the `/assets/js/dist` folder.

So locally, the only way those files exist is if you run `npm run build`.

Same with the GitHub Actions workflow, the [test step fails](https://github.com/joshjohanning/joshjohanning.github.io/actions/runs/4451432318/jobs/7818071037) b/c it's missing all of the minimized js in the dist folder.

**Comment by cotes2020** [comment]
See also: https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

**Comment by joshjohanning** [comment]
> See also: https://github.com/cotes2020/jekyll-theme-chirpy/wiki/Upgrade-Guide#upgrade-the-fork

ahh... didn't think to check the wiki.

so for the forked method, we need to check the `dist` folder in like before then.

**Comment by joshjohanning** [comment]
thank you! ✨

**Pull request closed without merging**
