### PR TITLE
Adjust font sizes of headings according to square roots to make them look better

### PR DESCRIPTION
**Pull request by v4vong**
## Description

Adjust font sizes of headings according to this algorithm:

```
H1 = 2/sqrt1 = 2
H2 = 2/sqrt2 = 1.414
H3 = 2/sqrt3 = 1.155
H4 = 2/sqrt4 = 1
H5 = 2/sqrt5 = 0.894
H6 = 2/sqrt6 = 0.816
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How has this been tested

- [ ] I have run `bash ./tools/test` (at the root of the project) locally and passed
- [x] I have tested this feature in the browser

### Test Configuration

- Browser type & version:
- Operating system:
- Ruby version: 
- Bundler version: 
- Jekyll version:

### CODE REVIEW

**Review by cotes2020 — COMMENTED** [review]
Hi there, as this PR involves layout design (beyond the scope of the contribution guidelines), may I ask if there is any theoretical support for this algorithm? If so, please let me know.

**Comment by v4vong** [comment]
> Hi there, as this PR involves layout design (beyond the scope of the contribution guidelines), may I ask if there is any theoretical support for this algorithm? If so, please let me know.

No theoretical support. I just think the size of `h3`, `h4`, and `h5` is too close according to current settings, it's hard to tell them apart by the naked eye. Then I want to use a specific rule to calculate the font size of headings, so as to avoid randomness. Of course, it does not have to use `sqrt`.

**Comment by cotes2020** [comment]
So I'm sorry, this modification will not be merged, but I will come up with a new way to make the size differences between headings more apparent.

**Comment by v4vong** [comment]
> So I'm sorry, this modification will not be merged, but I will come up with a new way to make the size differences between headings more apparent.

Cool. Looking forward to that.

**Pull request closed without merging**
